apiVersion: v1
kind: Service
metadata:
  name: meadstats-staging
spec:
  selector:
    app: meadstats
    env: staging
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meadstats-staging-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - staging.meadstats.com
    secretName: meadstats-staging-cert
  rules:
    - host: staging.meadstats.com
      http:
        paths:
        - backend:
            serviceName: meadstats-staging
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meadstats-staging-deployment
  labels:
    app: meadstats
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meadstats
      env: staging
  template:
    metadata:
      labels:
        app: meadstats
        env: staging
    spec:
      containers:
      - name: meadstats-staging
        image: docker.pkg.github.com/boren/meadstats-frontend/meadstats-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 30
          timeoutSeconds: 1
          initialDelaySeconds: 10
        ports:
        - containerPort: 5000
