apiVersion: v1
kind: Service
metadata:
  name: meadstats
spec:
  selector:
    app: meadstats
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meadstats-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  tls:
  - hosts:
    - meadstats.com
    - www.meadstats.com
    secretName: meadstats-prod-cert
  rules:
    - host: www.meadstats.com
      http:
        paths:
        - backend:
            serviceName: meadstats
            servicePort: 80
    - host: meadstats.com
      http:
        paths:
        - backend:
            serviceName: meadstats
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meadstats-deployment
  labels:
    app: meadstats
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  selector:
    matchLabels:
      app: meadstats
  template:
    metadata:
      labels:
        app: meadstats
    spec:
      containers:
      - name: meadstats
        image: hovedbore/meadstats-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 30
          timeoutSeconds: 1
          initialDelaySeconds: 10
        ports:
        - containerPort: 5000
